<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <BuiltInComInteropSupport>true</BuiltInComInteropSupport>
    <AvaloniaUseCompiledBindingsByDefault>true</AvaloniaUseCompiledBindingsByDefault>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../Augram.Core/Augram.Core.csproj" />
    <ProjectReference Include="../Augram.Engine/Augram.Engine.csproj" />
    <ProjectReference Include="../Augram.Platform.Windows/Augram.Platform.Windows.csproj" />
    <ProjectReference Include="../Augram.Platform.MacOS/Augram.Platform.MacOS.csproj" />
  </ItemGroup>
  <ItemGroup>
    <InternalsVisibleTo Include="Augram.App.Tests" />
  </ItemGroup>
  <ItemGroup>
    <AvaloniaResource Include="Assets/**" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Avalonia" />
    <PackageReference Include="Avalonia.Desktop" />
    <PackageReference Include="Avalonia.Themes.Fluent" />
    <PackageReference Include="CommunityToolkit.Mvvm" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" />
  </ItemGroup>
</Project>
