using Avalonia.Controls;
using Avalonia.Platform;

namespace Augram.App.Tray;

/// <summary>
/// The tray icons, generated by <c>tools/IconTool</c> from Joel's app icon (F7: the state must be unmistakable). Windows:
/// the full-colour icon when enabled, the same in dimmed grey when disabled, each an .ico with one exact image per display
/// scaling (16 px at 100 %, 20 at 125 %, …) so the tray is not shrunk from a larger image; the 32 px PNG is the fallback
/// if a backend cannot read the .ico. Linux: the PNGs. macOS: a menu-bar template image (black and alpha only,
/// <see cref="IsTemplate"/>) that the system tints for light and dark menu bars, dimmed when disabled.
/// </summary>
public sealed class TrayIconSet
{
    private TrayIconSet(WindowIcon enabled, WindowIcon disabled, bool isTemplate)
    {
        Enabled = enabled;
        Disabled = disabled;
        IsTemplate = isTemplate;
    }

    public WindowIcon Enabled { get; }

    public WindowIcon Disabled { get; }

    /// <summary>True on macOS: the tray must mark the image as a template so the menu bar tints it.</summary>
    public bool IsTemplate { get; }

    public static TrayIconSet Load() => Load(OperatingSystem.IsMacOS() ? TrayIconKind.MacTemplate : OperatingSystem.IsWindows() ? TrayIconKind.WindowsIco : TrayIconKind.Png);

    internal static TrayIconSet Load(TrayIconKind kind) => kind switch
    {
        TrayIconKind.MacTemplate => new(LoadIcon("tray-mac-enabled.png"), LoadIcon("tray-mac-disabled.png"), isTemplate: true),
        TrayIconKind.WindowsIco => new(LoadIcoOrPng("tray-enabled"), LoadIcoOrPng("tray-disabled"), isTemplate: false),
        _ => new(LoadIcon("tray-enabled.png"), LoadIcon("tray-disabled.png"), isTemplate: false),
    };

    /// <summary>The multi-size .ico, or the 32 px PNG when the backend cannot read it: a tray icon must never stop the app from starting.</summary>
    private static WindowIcon LoadIcoOrPng(string name)
    {
        try
        {
            return LoadIcon(name + ".ico");
        }
        catch (Exception exception) when (exception is not OutOfMemoryException)
        {
            return LoadIcon(name + ".png");
        }
    }

    private static WindowIcon LoadIcon(string file)
    {
        using var stream = AssetLoader.Open(new Uri("avares://Augram.App/Assets/" + file));
        return new WindowIcon(stream);
    }
}
