using Avalonia.Controls;
using Avalonia.Platform;

namespace Augram.App.Tray;

/// <summary>
/// The tray icons, generated by <c>tools/IconTool</c> from Joel's app icon (F7: the state must be unmistakable). Windows
/// and Linux: the full-colour icon when enabled, the same in dimmed grey when disabled. macOS: a menu-bar template image
/// (black and alpha only, <see cref="IsTemplate"/>) that the system tints for light and dark menu bars, dimmed when disabled.
/// </summary>
public sealed class TrayIconSet
{
    private TrayIconSet(WindowIcon enabled, WindowIcon disabled, bool isTemplate)
    {
        Enabled = enabled;
        Disabled = disabled;
        IsTemplate = isTemplate;
    }

    public WindowIcon Enabled { get; }

    public WindowIcon Disabled { get; }

    /// <summary>True on macOS: the tray must mark the image as a template so the menu bar tints it.</summary>
    public bool IsTemplate { get; }

    public static TrayIconSet Load() => Load(OperatingSystem.IsMacOS());

    internal static TrayIconSet Load(bool macOS) => macOS
        ? new(LoadIcon("tray-mac-enabled.png"), LoadIcon("tray-mac-disabled.png"), isTemplate: true)
        : new(LoadIcon("tray-enabled.png"), LoadIcon("tray-disabled.png"), isTemplate: false);

    private static WindowIcon LoadIcon(string file)
    {
        using var stream = AssetLoader.Open(new Uri("avares://Augram.App/Assets/" + file));
        return new WindowIcon(stream);
    }
}
